[WIP] support for projectile
ByteArena/backends pull request #20
Opened 2017-04-04 11:45 UTC by xtuc

2017-04-04 11:47 UTC, xtuc commented on server/swarmstate.go
> +			case "mutationShoot":
I will split this operation in two separate part:
- aim
- shoot

Or just shoot an use the velocity of the current agent.

2017-04-04 13:31 UTC, edi9999 commented on server/swarmstate.go
> +			case "mutationShoot":
I think it can be more complex (and thus more interesting) for agents if they can only shoot "in front of them". In the future, we could allow the agents to "move their gun" up to 15 degrees (so they still can shoot a little bit to the left or to the right).

2017-04-04 16:49 UTC, edi9999 requested changes

2017-04-04 16:49 UTC, edi9999 commented on agents/shooter/utils/comm.js
> +const net = require('net');
utils should be shared somehow, but to be done in a later PR maybe

2017-04-04 16:49 UTC, edi9999 commented on agents/shooter/client.js
> +      ['mutationShoot', attractorpos.toArray(5)],
since it is already sendMutations, I would prefer to just have 'shoot' instead of 'mutationShoot'

2017-04-04 16:49 UTC, edi9999 commented on cmd/arena/client/index.html
> +          let line = new PIXI.Graphics();
You can use const here :-)

2017-04-04 16:49 UTC, edi9999 commented on cmd/arena/main.go
> +				for _, state := range swarmstate.Projectiles {
`for _ ,state` -> `for _ , projectile`

2017-04-04 16:49 UTC, edi9999 commented on server/swarmstate.go
> +	for k, state := range swarmstate.Projectiles {
state->projectile

2017-04-04 16:49 UTC, edi9999 commented on server/swarmstate.go
> +			// state.Ttl --
Can we uncomment this ?

2017-04-04 16:49 UTC, edi9999 commented on server/swarmstate.go
> +						log.Panicln("Invalid mutationSteer argument")
-> Invalid mutationShoot

2017-04-04 16:49 UTC, edi9999 commented on server/swarmstate.go
> +						log.Panicln("Invalid mutationSteer argument")
-> `x` not defined in `mutationShoot`

2017-04-04 16:49 UTC, edi9999 commented on server/swarmstate.go
> +						log.Panicln("Invalid mutationSteer argument")
-> `y` not defined in `mutationShoot`

2017-04-04 16:49 UTC, edi9999 commented on server/swarmstate.go
> +						Position: utils.MakeVector2(agentX+newstate.Radius, agentY+newstate.Radius),
I don't think that you should be adding the Radius here.
I would expect that x:0, y : 0 means that the center of the circle is at 0,0 (it is the responsibility of the UI to show the sprites correctly)

2017-04-04 16:49 UTC, edi9999 commented on server/swarmstate.go
> +						Velocity: newstate.Position.Add(utils.MakeVector2(x, y)), // adding the agent position to "absolutize" the target vector
This seems strange : The key is called `Velocity`, however, with the operation that you do, it seems that what you are calculating is the aboslute position of the **Target**.

2017-04-04 16:50 UTC, edi9999 commented on agents/shooter/client.js
> +      ['mutationShoot', attractorpos.toArray(5)],
probably done later

2017-04-04 18:04 UTC, netgusto commented on agents/shooter/client.js
> +      ['mutationShoot', attractorpos.toArray(5)],
@edi9999 I agree; created issue #22

2017-04-04 18:12 UTC, netgusto commented on agents/shooter/utils/comm.js
> +const net = require('net');
Yup; created #23

2017-04-04 18:18 UTC, netgusto commented on server/swarmstate.go
> +						Position: utils.MakeVector2(agentX+newstate.Radius, agentY+newstate.Radius),
Yes, correct; It should be handled in the visualisation using Pixi Sprite::anchor
See http://pixijs.download/dev/docs/PIXI.Sprite.html#anchor

2017-04-06 07:44 UTC, netgusto commented on server/swarmstate.go
> +			// state.Ttl --
It is now commented; projectiles have a proper ttl.

2017-04-06 07:46 UTC, netgusto commented on server/swarmstate.go
> +			case "mutationShoot":
Yup; Issue #27 created.

2017-04-06 07:46 UTC, netgusto commented on server/swarmstate.go
> +						log.Panicln("Invalid mutationSteer argument")
Fixed.

2017-04-06 07:51 UTC, netgusto commented
Fixed points noted in review. Some points have been converted to issues.
Merging this to master to establish clean basis for next PRs (a lot of refactoring has happened in this PR).

2017-04-06 07:51 UTC, merged