Feat build git
ByteArena/backends pull request #51
Opened 2017-04-23 20:39 UTC by netgusto

2017-04-23 20:41 UTC, xtuc commented
I'll do a quick cleanup and then will lgtm

2017-04-23 20:43 UTC, netgusto commented on server/container/orchestrator.go
> +		Links:       nil,
woops :)

2017-04-23 20:43 UTC, netgusto commented on cmd/agent-builder/.gitignore
> +agent-builder
git rm --cached agent-builder + .gitignore

2017-04-23 20:46 UTC, netgusto commented on cmd/agent-builder/main.go
> +	dir := "/tmp/" + hash
Use https://golang.org/pkg/io/ioutil/#TempDir ?

2017-04-29 11:44 UTC, xtuc requested changes

2017-04-29 11:44 UTC, xtuc commented on docker-compose.dev.yml
> +      - private
Since every container are in the private network the host cannot call them (I might be wrong there). I created a so called jump-host or bastion to access the private network.

Current state of the union:

- Gandlaf mange users and repos - OK
- When you push to a repo it calls the webhook services - OK
- The webhook service ask the agent-builder to create the corresponding image - KO
   - The agent-builder cannot clone the repo missing a private key
- Image pushed to the repository - ?

2017-04-29 11:44 UTC, xtuc commented on docker/webhook/hooks.json
> +      { "source": "string", "name": "http://agentbuilder/build/xtuc/agent" }
Since this commit the webhook stoped working

2017-04-29 11:44 UTC, xtuc commented on docker-compose.dev.yml
>        - ./data/repositories:/home/git/repositories
Repositories are persistent, Gandalf's database (MongoDB) must be as well!

2017-04-29 12:17 UTC, netgusto commented on docker-compose.dev.yml
> +      - private
> The agent-builder cannot clone the repo missing a private key

Yes, we have to provide a private key (as an env variable ?) to `agent-builder`, that will allow git cloning on gandalf (BA key)

2017-04-29 12:18 UTC, netgusto commented on docker/webhook/hooks.json
> +      { "source": "string", "name": "http://agentbuilder/build/xtuc/agent" }
Yes ? You mean the container won't boot, or the webhook has no effect ?

2017-04-29 12:21 UTC, xtuc commented on docker/webhook/hooks.json
> +      { "source": "string", "name": "http://agentbuilder/build/xtuc/agent" }
The container does boot but I believe the hook wasn't found last time I tried.

2017-04-29 12:22 UTC, xtuc commented on docker-compose.dev.yml
> +      - private
Yes, I also want to remove password authentication on the SSHd since it's useless and a good security practice.

2017-05-28 07:22 UTC, xtuc commented on cmd/arena/config.json
> +    "git": "git@github.com:netgusto/bytearena-agent-seeker.git",
Can be removed

2017-05-28 07:35 UTC, merged